spring:
  config:
    activate:
      on-profile: dev

  devtools:
    add-properties: true

  datasource:
    url: jdbc:sqlserver://${DB_HOST:}:${DB_PORT:1433};databaseName=${DB_NAME:CineShow};encrypt=true;trustServerCertificate=true
    username: ${DB_USER:}
    password: ${DB_PASS:}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: "manhphongg6572@gmail.com"


admin: { email_default: "manhphong6572@gmail.com", password_default: "12345678" }

